default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: manage_development
  username: postgres
  password: root
  port: 5434

test:
  <<: *default
  database: manage_test
  username: postgres
  password: root
  port: 5434

production:
  <<: *default
  database: manage_production
  username: manage
  password: <%= ENV['MANAGE_DATABASE_PASSWORD'] %>
