# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0a350301ea52dc8647011a9c3cde9cdf703821ed05cd4b0efc52c5dea206e811735e36328ecb3da5805fc5bd725b5c1e914518929dd17f44be8bf4cf957ec8f1

test:
  secret_key_base: baca6f7b3595c90f3bed8d846f3a760899eec418e69b504948d50e6259efb4c36674ababccfdb44a5e81aa0d980280fac216c4f9f9442638b0b99a5739cc923d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
